### ISSUE TITLE
文档细节可能出错

### ISSUE THREAD

**Issue by guanyuqian** [hurley25/wiki#5]
@hurley25 
《hurlex <五> 相关库函数和调试打印函数》中的
“一个函数想使用ebx寄存器那么必须在返回前恢复ebp原先的值”
是不是应该写为
“一个函数想使用ebp寄存器那么必须在返回前恢复ebp原先的值”

**Comment by hurley25** [comment]
是的，欢迎提 Pull requests 修改这个错误
